# Generated by Django 6.0.3 on 2026-03-27 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('party', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parti politique ou Description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Programme / Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=50, unique=True, verbose_name="Numéro de carte d'identité (NIN) ou Matricule")),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('pin', models.CharField(help_text="Sera utilisé avec le NIN pour s'authentifier", max_length=10, verbose_name='Code PIN secret')),
                ('has_voted', models.BooleanField(default=False, verbose_name='A déjà voté ?')),
            ],
            options={
                'verbose_name': 'Électeur',
                'verbose_name_plural': 'Électeurs',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure du vote')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.candidate', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
